/*
 * ComStack_Cfg.h
 *
 *  Created on: May 4, 2018
 *      Author: Ahmed Usama Khalifa
 */

#ifndef INCLUDES_COMSTACK_CFG_H_
#define INCLUDES_COMSTACK_CFG_H_

/*
 * ComStack_Cfg.h shall be generated by the generator to generate /
 * the type definition of the PduIdType and PduLengthType from the/
 * EcuC Virtual Layer based on the configuration e.g. typedef uint8/
 * PduIdType if number of PDUs are less than 256
 */

typedef uint32_t PduLengthType_t;

typedef enum {
    BUFREQ_OK = 0, // Data has been copied to the transmit buffer completely as requested
    /*
     * Request could not be fulfilled, because the required amount of Tx data is not available.
     * The lower layer module may retry this call later on. No data has been copied.
     */
    BUFREQ_E_BUSY,
    BUFREQ_E_NOT_OK // Data has not been copied. Request failed
} BufReq_ReturnType_t;



#endif /* INCLUDES_COMSTACK_CFG_H_ */
