function formatXml(xml, tab) { // tab = optional indent value, default is tab (\t)
    var formatted = '', indent= '';
    tab = tab || '\t';

    xml.split(/>\s*</).forEach(function(node) {
        if (node.match( /^\/\w/ )) indent = indent.substring(tab.length); // decrease indent by one 'tab'
        formatted += indent + '<' + node + '>\r\n';
        if (node.match( /^<?\w[^>]*[^\/]$/ )) indent += tab;              // increase indent
    });

    // remove un-used space whose generated by `XML.WriteString`
    if(window.closer != undefined) {
    	var changer = window.closer + '\n ';
    	formatted = formatted.split(changer).join('');
    }

    return formatted.substring(1, formatted.length-3);
}